{application,mesh,
             [{modules,['Elixir.Mesh','Elixir.Mesh.Actors.ActorOwner',
                        'Elixir.Mesh.Actors.ActorOwnerSupervisor',
                        'Elixir.Mesh.Actors.ActorSupervisor',
                        'Elixir.Mesh.Actors.ActorSystem',
                        'Elixir.Mesh.Actors.ActorTable',
                        'Elixir.Mesh.Actors.VirtualTestActor',
                        'Elixir.Mesh.Cluster.Capabilities',
                        'Elixir.Mesh.Cluster.Membership',
                        'Elixir.Mesh.Shards.ShardConfig',
                        'Elixir.Mesh.Shards.ShardRouter',
                        'Elixir.Mesh.Supervisor']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,libcluster]},
              {description,"Mesh is a distributed actor system for Elixir with automatic sharding,\nclustering support, and built-in supervision.\n"},
              {registered,[]},
              {vsn,"0.1.0"}]}.
